<?xml version="1.0" encoding="utf-8"?><testsuite errors="1" failures="0" name="pytest" skips="0" tests="1" time="0.529"><testcase classname="" file="pytests/test_index.py" name="pytests.test_index" time="0"><error message="collection failure">pytests/test_index.py:6: in &lt;module&gt;
    import ipynb.fs.full.index
index.ipynb:236: in &lt;module&gt;
    {
E   NameError: name &apos;restauran_list&apos; is not defined</error></testcase></testsuite>